### ISSUE TITLE
Keep elastic API contracts regarding GET/PUT actions

### ISSUE THREAD

**Issue by jgprogramming** [opendistro-for-elasticsearch/index-management#102]
## Expected Behavior
`GET _opendistro/_ism/policies` returns list of created policies

## Current Behavior
```
{
  "error": "Incorrect HTTP method for uri [/_opendistro/_ism/policies?pretty] and method [GET], allowed: [PUT]",
  "status": 405
}
```

**Comment by avsamit6600** [comment]
I am observing the same behavior. I am running the request as an administrator.

**Comment by dbbaughe** [comment]
Hi @avsamit6600,

This is expected, we currently only have a PUT API for /policies and have been using normal ES queries for the equivalent of GET /policies. You can do the same for now until we eventually add a GET /policies API.

**Comment by Rymev** [comment]
Hello,

I'm also looking for a way to retrieve a list of all policies. It sounds like you have a workaround with "normal ES queries", I did try some queries but didn't have it. Have you got some explanation ?

Thank you in advence for your response!

**Comment by dbbaughe** [comment]
Hi @Rymev,

All of the policies and managed indices are stored in a `.opendistro-ism-config` index.
They are namespaced by the top level field, so if you want to get a list of all policies you can do something like:
```
GET .opendistro-ism-config/_search
{
  "query": {
    "exists": {
      "field": "policy"
    }
  }
}
```
You can modify size, from, sort, add more query clauses, etc.
We'll turn this into a GET policies API too, but for now using native elasticsearch queries works.

**Comment by dbbaughe** [comment]
We have added the GET policies API: https://github.com/opendistro-for-elasticsearch/index-management/commit/2f7d778a4447e7c64b3e57fac54e08f8ae3829b6
It will be included in the upcoming release.
