### ISSUE TITLE
Implement allocation action

### ISSUE THREAD

**Issue by jgprogramming** [opendistro-for-elasticsearch/index-management#103]
## Expected Behavior
Our opendistro cluster has two data node types: `hot` and `warm`. For each index we have varied retention times for hot and warm boxes so we using curator for this task gets tiresome. We'd like to use ILM for that task.

We expect that policy for allocate will look like:
```
{
    "allocation": {
        "require": { "box_type": "hot" }
    }
}
```

It's also a good idea to provide `include` and `exclude` filters.

## Current Behavior
allocate action is not implemented

**Comment by dbbaughe** [comment]
Steps required:
[AttemptAllocationStep] -> Set the allocation index/shard filtering settings
[WaitForAllocationStep] -> Wait for shards to actually allocate to nodes

Settings:
"require"
"include"
"exclude"
"wait_for"

**Comment by dabr-grapeup** [comment]
Hi @dbbaughe, I've a question about logic for WaitForAllocationStep, what API endpoints should be use to validate that? For me it's not clear how can I test if the current node matches allocation settings (require, include, exclude).

**Comment by dabr-grapeup** [comment]
I've opened a PR with my changes regarding implementation of `AttemptAllocationStep`.

**Comment by lolcatlolcat** [comment]
I'm assuming this is actively being worked on? Because we have similar requirements as well and would love to use ISM in our hot -> warm -> cold architecture in-lieu of the python script we have now.

**Comment by jgprogramming** [comment]
Hi @alolita , any news regarding this feature? It's been over three months since this PR.

**Comment by alexkleinfig** [comment]
It would be great.
I'am just waiting for this feature to migrate our classic 10To elk stack to opendistro

**Comment by jgprogramming** [comment]
Hey @dbbaughe, can you take a look at this one? PR is stuck since October.

**Comment by dbbaughe** [comment]
Hey @jgprogramming,

I will be picking this up as one of my next tasks. I believe it was only blocked because we need to add multi-node integration tests into the gradle tasks. Once I get that added then we'll just need the PR updated and we can merge.

Thanks

**Comment by sgavrylenko** [comment]
Hi guys! 
As I understand, this feature is described on doc page (https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/cluster/) about cluster configuration, but not implemented yet?

From that page
`A popular approach is to configure your index templates to set the index.routing.allocation.require.temp value to hot. This way, Elasticsearch stores your most recent data on your hot nodes.

You can then use the Index State Management (ISM) plugin to periodically check the age of an index and specify actions to take on it. For example, when the index reaches a specific age, change the index.routing.allocation.require.temp setting to warm to automatically move your data from hot nodes to warm nodes.`

If I'm wrong, please tell me, how I can move indices from hot to warm nodes with ISM

**Comment by jsirianni** [comment]
I am having the same issue as sgavrylenko. I am reviewing the ISM documentation, and I am not sure how I am supposed to specify `index.routing.allocation.require` in a policy. 

Step 1) New index is created with `index.routing.allocation.require.tier=hot`, where `tier` is an arbitrary node attribute that I use in my environment. I have nodes with tier=hot, tier=warm. 

Strep 2) Define a policy that updates `index.routing.allocation.require.tier` to `warm` after N days.

The documentation makes it clear that this is the approach to take, but I do not see any documentation on how to add this part to the policy. Maybe I am not missing it? 
```
For example, when the index reaches a specific age, change the index.routing.allocation.require.temp setting to warm to automatically move your data from hot nodes to warm nodes.
```

**Comment by dbbaughe** [comment]
Hi @jsirianni,

Did not see that in the documentation, it should not be there as the Allocation action has not yet been added to ISM. This is a miss on our part, thanks. We will update the documentation and try to prioritize the Allocation PR.
