### ISSUE TITLE
index_management plugin 1.3.0.0 is not compatible with ODFE1.2.x

### ISSUE THREAD

**Issue by arnitolog** [opendistro-for-elasticsearch/index-management#118]
It looks like index_management plugin 1.3.0.0 is not compatible with ODFE1.2.x
Tried both ODFE 1.2.0 and 1.2.1 with the same result. 
Does it make sense to try to rebuild a plugin or ODFE 1.3 is going to be released soon? 
Here is an error I got when tried to build a docker:

```
Step 1/3 : FROM amazon/opendistro-for-elasticsearch:1.2.0
1.2.0: Pulling from amazon/opendistro-for-elasticsearch
...
Digest: sha256:5ebf61c123315627934a381a07eea6482cbff69883de821306da19a4f98eb057
Status: Downloaded newer image for amazon/opendistro-for-elasticsearch:1.2.0
 ---> 79f55ffa040a
Step 2/3 : COPY ./opendistro_index_management-1.3.0.0.zip /tmp
 ---> c268405a8707
Step 3/3 : RUN bin/elasticsearch-plugin install file:///tmp/opendistro_index_management-1.3.0.0.zip --batch
 ---> Running in 76718678c6f7
-> Downloading file:///tmp/opendistro_index_management-1.3.0.0.zip
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [opendistro_index_management] was built for Elasticsearch version 7.3.2 but version 7.2.0 is running
     at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:346)
```

**Comment by chuanzgh** [comment]
Well, the error message clearly says
`Plugin [opendistro_index_management] was built for Elasticsearch version 7.3.2 but version 7.2.0 is running`
So there's that. You can't slap a thing on something it's not designed for and call it broken when it doesn't work.

**Comment by arnitolog** [comment]
ok. But there is no version for ODFE 1.2. So not index_management plugin 1.1.0.0 nor index_management plugin 1.3.0.0 support ODFE 1.2

**Comment by qreshi** [comment]
Hey @arnitolog, sorry about that, it seems the lack of releases caused the confusion that there was no Index Management support for ES 7.2. I've updated the releases.

[v1.2.0.0](https://github.com/opendistro-for-elasticsearch/index-management/releases/tag/v1.2.0.0) for ES 7.2.0

[v1.2.1.0](https://github.com/opendistro-for-elasticsearch/index-management/releases/tag/v1.2.1.0) for ES 7.2.1

I will update the Index Management Kibana releases when I get the chance as well but this should help you out with the issue above.

**Comment by arnitolog** [comment]
thank you @qreshi. Also, do you know when ODFE 1.3 is going to be released?

**Comment by dbbaughe** [comment]
Closing this as ISM 1.2.x releases are available. They will not be included in the official ODFE1.2.x distribution as of now, so you'll have to follow the steps in documentation to add it as a new plugin.
