### ISSUE TITLE
Action timed out

### ISSUE THREAD

**Issue by arnitolog** [opendistro-for-elasticsearch/index-management#130]
**Describe the bug**
Hello
I have several indices with Action timed out.
But when I executed explain I found that consumed_retries = 0. Does it mean that Action was tried only 1 time, or consumed_retries parameter means something different?
Here is the state of the index:
![image](https://user-images.githubusercontent.com/34036079/71965220-f1bbd480-3207-11ea-936a-04fc2ac2bf01.png)
Here is output for _ism/explain:
```
{
“logging-time-2019.10.28” : {
“index.opendistro.index_state_management.policy_id” : “ingest_policy”,
“index” : “logging-time-2019.10.28”,
“index_uuid” : “Qy2JLOzJScG_xha1XowwFw”,
“policy_id” : “ingest_policy”,
“policy_seq_no” : 2613,
“policy_primary_term” : 56,
“transition_to” : “delete”,
“retry_info” : {“failed” : false, “consumed_retries” : 0 },
“info” : { “message” : “Action timed out” }
}
}
```
and here is the policy itself:
```
{
“policy_id”: “ingest_policy”,
“description”: “Default policy”,
“last_updated_time”: 1574536845562,
“schema_version”: 1,
“error_notification”: null,
“default_state”: “ingest”,
“states”: [{
“name”: “ingest”,
“actions”: [],
“transitions”: [{ 
“state_name”: “search”,
“conditions”: { “min_index_age”: “4d” }
}]
},
{
“name”: “search”,
“actions”: [{
“timeout”: “1h”,
“retry”: {“count”: 3,“backoff”: “constant”,“delay”: “1h”},
“force_merge”: { “max_num_segments”: 1 }
}],
“transitions”: [{
“state_name”: “delete”,
“conditions”: { “min_index_age”: “60d” }
}]
},
{
“name”: “delete”,
“actions”: [{
“timeout”: “1h”,
“retry”: {“count”: 3,“backoff”: “constant”,“delay”: “1h”},
“delete”: {}
}],
“transitions”: []
}
]}
```

**Comment by dbbaughe** [comment]
Hi @arnitolog,

Thanks for opening the issue.

One thing to note is you have retry counts of 3 with a delay of 1h and a timeout of 1h. So if any of those actions w/ those retry/timeout settings failed, the next execution would wait for an hour, at which point it has now timed out and would fail the policy/managed index. So for starters you could either tweak the delay or timeout (whichever makes most sense for your data).

As for why this one timed out on the first try, if you have the audit logs available in the audit history index `.opendistro-ism-managed-index-history*` could you paste them here? Would like to see the execution order if possible. Otherwise will try to reproduce on my end, thanks!

**Comment by arnitolog** [comment]
Hello @dbbaughe 
Thanks for your response. I changed the timeout to 4 hours. But got the same result: "Action timeout"
Here are audit logs for the similar case:
![image](https://user-images.githubusercontent.com/34036079/72204289-d8708d80-347e-11ea-9f0f-44b76ab45a2a.png)
![image](https://user-images.githubusercontent.com/34036079/72204296-e3c3b900-347e-11ea-8fcf-d8fc2e13d298.png)

and here we can see that action was marked as "Action timed out" in 5 minutes after start and 
 consumed_retries=0

**Comment by dbbaughe** [comment]
Thanks for providing the information @arnitolog.

It looks like the action timed out logic is using the previous action's metadata on the first execution.
In your example you have transition to search after 4 days, and then the first action in search times out after 1h. But, it used the action starting time from the previous action (transition, 4 days ago) and failed immediately.

You can remove the timeout(s) or increase the timeout(s) affected by the above for now, will have a fix in early next week.

Thanks!

**Comment by arnitolog** [comment]
Hello @dbbaughe 

Thanks a lot for your help. And many thanks for this awesome product

**Comment by dbbaughe** [comment]
Thanks @arnitolog!

This has been fixed: https://github.com/opendistro-for-elasticsearch/index-management/pull/133
We'll backport it to earlier versions soon.
