### ISSUE TITLE
[BUG] Update policy doesn’t work

### ISSUE THREAD

**Issue by arnitolog** [opendistro-for-elasticsearch/index-management#131]
**Describe the bug**
Hello.
It looks like update policy REST API doesn’t work.
I have an index with a policy named “ingest_policy”. And the policy was updated recently.
When I tried to update the index via REST I got an error:
`{ “error”: “no handler found for uri [/_opendistro/_ism/update_policy/logging-price-2019.11.12?pretty] and method [POST]” }`

Here is the query that I ran:
```
POST _opendistro/_ism/update_policy/logging-price-2019.11.12
{ “policy_id”: “ingest_policy”}
```
At the same time it works fine via UI
I’m running OpenDistro 1.3

**Comment by dbbaughe** [comment]
Hi @arnitolog,

Update is a PUT operation for our API. You also need to provide the seq_no and primary_term in the query parameters for the update operation to succeed.
You can refer to the documentation and full examples here:
https://opendistro.github.io/for-elasticsearch-docs/docs/ism/api/#update-policy

Thanks,
Drew
