### ISSUE TITLE
Implement recovery priority action

### ISSUE THREAD

**Issue by gittygoo** [opendistro-for-elasticsearch/index-management#142]
Expected Behavior
Our opendistro cluster has two data node types: hot and warm. 

The Index lifecycle tool from Elastic allows the setting of a recover priority with “set_priority”. https://www.elastic.co/guide/en/elasticsearch/reference/master/_actions.html

Current Behavior
priority action is not implemented

**Comment by dbbaughe** [comment]
This has been merged and will be released with 1.9
