### ISSUE TITLE
Question - applying policies to multiple indices using regex match

### ISSUE THREAD

**Issue by gplechuck** [opendistro-for-elasticsearch/index-management#143]
Hi there, 

Is it possible to apply policies to multiple indices using a regex match? I see that policies can be applied to index pattern names using a wildcard but am unsure how to apply a policy using a more fine grained index pattern match.

Eg - 

Assume I wanted to update the policies for all 'index-pattern-YYYY.MM.DD' indices but not for 'index-pattern-*-YYYY.MM.DD' and ran the following -  

```
curl  -X POST_opendistro/_ism/change_policy/index-pattern-* -d @change-policy.json 

----
change-policy.json
{                                                                                                                              
        "policy_id": "new-policy"                                                                                                                                                                               
}              
```

This would update all indices starting with index-pattern of course, including the ones I would not like to match.
Is there any filter that could be placed in the body of the json request that would restrict  the change_policy operation to indices matching a regex match? 

Cheers

**Comment by gplechuck** [comment]
Solved my own requirements by including an exclusion wildcard match also, eg - 

`curl  -X POST_opendistro/_ism/change_policy/index-pattern-*,-index-pattern-*-* -d @change-policy.json `

Leaving the question open to see if using a regex match is supported, thanks.

**Comment by dbbaughe** [comment]
Hi @gplechuck,

We support native index matching:
https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html

There is currently no regex support.
