### ISSUE TITLE
Multi-node integration tests

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/index-management#145]
We currently have [Allocation PR](https://github.com/opendistro-for-elasticsearch/index-management/pull/106) blocked because there are no tests written.

Developer can't write tests because we do not have multi node integration test support currently.
We have seen issues in other plugins where they pass integration tests for single node cluster and fail for multi-node, so ideally we should have our integration tests run through both setups.

**Comment by dabr-grapeup** [comment]
Hi @dbbaughe , I did some research on that topic. 

ElasticSearch test library include this annotation:
`@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST, minNumDataNodes = 2)`, but it doesn't work.

I also tried to change general settings of gradle task to:
```
integTestCluster {
    distribution = "oss-zip"
    numNodes = 2
    // Temporary until job-scheduler is published to Maven
    setupCommand('installPlugin', 'bin/elasticsearch-plugin', 'install',
            "file://${fileTree("src/test/resources/job-scheduler").getSingleFile().absolutePath}")
}
```
But it crashes with strange error:
```
Testing started at 17:19 ...
> Configure project :
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.4.1
  OS Info               : Mac OS X 10.15.3 (x86_64)
  JDK Version           : 12 (AdoptOpenJDK 12.0.2 [OpenJDK 64-Bit Server VM 12.0.2+10])
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/adoptopenjdk-12.jdk/Contents/Home
  Random Testing Seed   : 7352E68AF40BEF80
=======================================
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/danielbryla/workspace/index-management/build.gradle' line: 181
* What went wrong:
Failed to notify build listener.
> Could not create task ':integTestCluster#wait'.
   > Task with name 'integTestCluster#installOpendistroForElasticsearchIndexManagementPlugin' not found in root project 'opendistro-for-elasticsearch-index-management'.
> Task with name 'integTestCluster#stop' not found in root project 'opendistro-for-elasticsearch-index-management'.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 2s
```

Any idea what can be an issue for any of those?

**Comment by dbbaughe** [comment]
Hi @dabr-grapeup,

The ESIntegTestCase is for an embedded cluster which Elastic recommends against using. It's more if you need to hook into any of the internals of a cluster it seems. We only use the rest test class for our integration tests.

I believe I was able to originally get the multi node cluster up and running before, but was pulled onto something else and wasn't able to finish it.

The current version upgrade that is happening has us upgrading to the new testing framework. It seems like the new testing framework will simplify the multi-node testing for us, but it also means it would only be from versions 7.5+. That means it might be easier to introduce the Allocation action into versions 7.5+ once we have that ready, but at the same time it wouldn't be available in the previous versions as we don't plan to backport every new action to every previous version. Will upgrading to the newer 7.5+ version be easy for you or are you locked to a previous version?

**Comment by dabr-grapeup** [comment]
From my perspective I don't see a problem here, however not sure if whole community can upgrade to 7.5+.

**Comment by dbbaughe** [comment]
Multi-node integration tests was recently added in
https://github.com/opendistro-for-elasticsearch/index-management/pull/254
https://github.com/opendistro-for-elasticsearch/index-management/pull/256
