### ISSUE TITLE
Documentation improvement: implications of actions

### ISSUE THREAD

**Issue by micha558** [opendistro-for-elasticsearch/index-management#160]
**Is your feature request related to a problem? Please describe.**
I am currently designing the policies for an elastic cluster and see several actions where I do not fully understand what implications they have. E.g. the close action closes the index (ok - reasonable) - but is a search after that possbile (the index is reopened on demand and closed again) or is it intended as an archive which has to be manually transitioned if needed

**Describe the solution you'd like**
I would like to have in https://opendistro.github.io/for-elasticsearch-docs/docs/ism/policies/#actions for each action a clear description
- what the action does
- what it implies (e.g. on search the index is first automatically opened and loaded leading to a delay of some seconds / a search is not possible. To be searchable again it has to be manually reopend by the open action via an e.g. manually triggered transition)
- what are typical case to use this action

**Describe alternatives you've considered**
Alternative would be to do some deep tests or try to find it out in the source code

**Additional context**
This request targets only at the documentation and does not include requests for code changes

**Comment by dbbaughe** [comment]
Hi @micha558,

The actions we have right now are just native elasticsearch operations (minus Notification). Some of the actions can have a very large documentation surrounding them (that is less related to ISM itself and more about that native operation). These answers can be be found in the elasticsearch documentation. I think a brief description would be helpful, but don't think we want to deal with all the implications of what calling native elasticsearch operations entails. Can ping our technical writers and check with them though.

Hey @aetter (can't find ashwin's alias), any thoughts on this issue?

**Comment by aetter** [comment]
@dbbaughe, we're still working on building out our OSS Elasticsearch content, but I completely agree with the sentiment. In this case, the good news is that only a few actions require further explanation: Force merge, replica count, close, and rollover.

Force merge and rollover are fairly complex, so we need to just add content for them to the [Elasticsearch](https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/) section. Replica count, we have some content and can link to it. Close is pretty straightforward, so I think another sentence or two here would do the trick.

Adding @ashwinkumar12345 to make the replica count and close changes. I think force merge and rollover will have to go into our broader documentation backlog.

**Comment by micha558** [comment]
> Force merge and rollover are fairly complex, so we need to just add content for them to the Elasticsearch section. Replica count, we have some content and can link to it. Close is pretty straightforward, so I think another sentence or two here would do the trick.

> I think a brief description would be helpful, but don't think we want to deal with all the implications of what calling native elasticsearch operations entails.

OK - under this circumstances I aggree, that a brief description and a link/note for further details is sufficient. One/two sentences for close (and perhaps open) would be great.

Thanks for your efforts!

Regards Michael
