### ISSUE TITLE
Action timeout [BUG]

### ISSUE THREAD

**Issue by arnitolog** [opendistro-for-elasticsearch/index-management#162]
**Describe the bug**
I faced with Action timeout again. 
Here is my policy:
`{
    "policy_id": "standard_policy",
    "description": "Default policy",
    "last_updated_time": 1584712848745,
    "schema_version": 1,
    "error_notification": null,
    "default_state": "rollover",
    "states": [{
            "name": "rollover",
            "actions": [{
                    "timeout": "24h",
                    "retry": {
                        "count": 20,
                        "backoff": "constant",
                        "delay": "1h"
                    },
                    "rollover": {
                        "min_size": "25gb",
                        "min_index_age": "7d"
                    }
                }],
            "transitions": [{
                    "state_name": "search",
                    "conditions": { "min_index_age": "7d" }
                }]
        },
        {
            "name": "search",
            "actions": [],
            "transitions": [{
                    "state_name": "delete",
                    "conditions": { "min_index_age": "37d" }
                }]
        },
        {
            "name": "delete",
            "actions": [{
                    "timeout": "24h",
                    "retry": {
                        "count": 20,
                        "backoff": "constant",
                        "delay": "1h"
                    },
                    "delete": {}
                }],
            "transitions": []
        }]
}`
and despite the timeout configuration, I've got Action timeout for several indices that use that policy. And it looks like the ssytem didn't perform any retries:
here is explain output
`{
  "logging-time-000001" : {
    "index.opendistro.index_state_management.policy_id" : "standard_policy",
    "index" : "logging-time-000001",
    "index_uuid" : "bUtoGJeyReeVKv3z1YCooA",
    "policy_id" : "standard_policy",
    "policy_seq_no" : 25472,
    "policy_primary_term" : 93,
    "rolled_over" : false,
    "state" : {
      "name" : "rollover",
      "start_time" : 1584715154862
    },
    "action" : {
      "name" : "rollover",
      "start_time" : 1584715454733,
      "index" : 0,
      "failed" : true,
      "consumed_retries" : 0,
      "last_retry_time" : 0
    },
    "retry_info" : {
      "failed" : false,
      "consumed_retries" : 0
    },
    "info" : {"message" : "Action timed out"}
  }
}`

**Desktop (please complete the following information):**
 - Opendistro Version 1.4.0

**Comment by dbbaughe** [comment]
Hi @arnitolog,

The timeout is the global timeout for the action before it is considered failed.
A timed out action is not retried, instead an action is retried if it failed and it will consume your retries up to the retry number or the timeout.

So your policy is set to completely fail the rollover action once it reaches 24 hours since attempting to rollover.

**Comment by arnitolog** [comment]
Yeah, it makes sense. Thanks for the explanation @dbbaughe
