### ISSUE TITLE
How to add rollover policy for alias instead of index

### ISSUE THREAD

**Issue by satyabhama** [opendistro-for-elasticsearch/index-management#221]
How can we add rollover policy to index template so that we can add for all index pattern

**Comment by dbbaughe** [comment]
Hi @satyabhama,

You should be able to use something like below to automatically apply a policy that contains rollover to a group of indices.

```
PUT _template/template_1
{
  "index_patterns": ["your_index_pattern-*"],
  "settings": {
    "opendistro.index_state_management.policy_id": "ingest_policy",
    "opendistro.index_state_management.rollover_alias": "some_alias"
  }
}
```

https://opendistro.github.io/for-elasticsearch-docs/docs/ism/api/#add-policy-at-index-creation
```
PUT your_index_pattern-1
{
  "settings": {
    "opendistro.index_state_management.policy_id": "ingest_policy",
    "opendistro.index_state_management.rollover_alias": "some_alias"
  },
  "aliases": {
    "some_alias": {
      "is_write_index": true
    }
  }
}
```
This will create a template that matches all future indices created from rollover and automatically apply your policy and add the rollover_alias.

The rollover request made by ISM will handle moving the write alias to the new index for you.

You'll want to be careful about using something like just `*` in your index_pattern as it can match system level indices (ones starting with a period) that you don't intend to have managed by ISM.
