### ISSUE TITLE
Can we create index and indices policies using Cloud formation template

### ISSUE THREAD

**Issue by satyabhama** [opendistro-for-elasticsearch/index-management#223]
Can we create index and indices policies using Cloud formation template?
If yes could you please provide example to add rollover policy

**Comment by dbbaughe** [comment]
Hi @satyabhama,

As far as I'm aware you cannot create indices using CloudFormation. That is used for infrastructure/configuration.

If you have any other questions about using ISM please post them on the forums here:
https://discuss.opendistrocommunity.dev/
