### ISSUE TITLE
[BUG] Kibana Index management opendistro aws elasticsearch 7.4

### ISSUE THREAD

**Issue by R00T88** [opendistro-for-elasticsearch/index-management#224]
Hi all,
i have deployed aws elastichsearch 7.4 with opendistro Fine–grained access control with internal database.
i'm able to create index and upload doc without any problem but im not able as master user to view indices under index management tab to apply indices policy to them.

How can i view al indices present into it?

Thanks

**Comment by dbbaughe** [comment]
Hi @R00T88,

The FGAC plugin seems to be doing something to searches done by ISM Kibana using the wildcard queries. I have experienced this before too and notice it goes away after a while (i.e. it starts working as expected). We can try to rewrite the queries being executed to get around this, but it would be also best for the FGAC plugin to fix this since it's an issue across all plugins.

**Comment by R00T88** [comment]
Hi @dbbaughe ,
how do you get it working?

If i deliver an aws elasticsearch 7.4 without enabling FGAC i can see all indices under "Index management" tab and i can apply policyc to them

i try to delivery another aws elasticsearch 7.4 with FGAC enabled but still have same issue so cannot see indices under "Index management" tab

@dbbaughe in aws elasticsearch + opendistro when i create index i can i automatically apply index policy?

Thanks

**Comment by dbbaughe** [comment]
Hi @R00T88,

We can first confirm if it's the same issue I experienced or if it's something else.
The issue I had was that the ISM Kibana query being executed contained two wildcards `**` that for some reason returned back no results.

Could you on Kibana DevTools try running both these queries:
```
// This should give you your full list of indices
GET _cat/indices/*

// This should not if you are running in to the same issue
GET _cat/indices/**
```

And verify if it is also not giving you the full list of indices. If using the ** does give you the full list, just do one last check on ISM Kibana and verify you can't see them.

**Comment by R00T88** [comment]
Hi @dbbaughe,
both query give me full index list and i try with curl too with master user and get all indices list (total 10 indices)
i came back to Index management into kibana with master user and i can see only one index referring to my master user --> .kibana-12442454456-xxxxx
i cannot see indices that i uploda into elasticsearch.

If i can see all inidices via curl with master user i don't think its a permission/role issue because im not able to see all inidces only in index management tab of kibana

Thanks

**Comment by dbbaughe** [comment]
Hi @R00T88,

Can you start typing one of your index names into the Index search input box and see if it returns?
Or does it also not return anything?

**Comment by R00T88** [comment]
Hi @dbbaughe ,
if i search index name into Index search input box i got it!
if i clear index search input box i got nothing!

Thanks

**Comment by R00T88** [comment]
Hi @dbbaughe 
i have i think the same issue as you

![image](https://user-images.githubusercontent.com/9050487/82088111-74dac300-96f1-11ea-9c3c-874f1e3bbfb2.png)

![image](https://user-images.githubusercontent.com/9050487/82088133-7f955800-96f1-11ea-8c9e-11d1f8aecbe8.png)

**Comment by dbbaughe** [comment]
@R00T88 awesome, thanks for the confirmation.

So a couple things:
1. I have seen this go away after x number of minutes, but I don't really know what the exact condition to get rid of the problem was. I don't know if it was simply time or I did something specific on Kibana.
2. I can update the ISM Kibana code to not do a _search/** although it was just easier to write the query that way as I was wrapping wild cards around the different search inputs.
3. The security plugin team needs to address this because it's definitely not normal behavior.

**Comment by R00T88** [comment]
@dbbaughe will you release this fix to aws opendistro too (because im using that :)) ?

i have another question, how can i automatically attach index policy while creating index into aws?
im using _bulk to stream aws cloudwatch logs into es

Thanks

**Comment by R00T88** [comment]
Hi @dbbaughe 
from today start working as espected but i don't change anything

**Comment by dbbaughe** [comment]
Hey @R00T88,

Yes, anything we fix/change will be released in ODFE.

For attaching a policy to an index during creation you can either specify the settings directly in the create index request or if you let Elasticsearch handle the index creation you can use index templates to match your index patterns and have settings automatically applied.

And thanks for the info, I'm assuming it's the same issue I've run in to. I have pinged an engineer from the security team to also take a look.

**Comment by dbbaughe** [comment]
This was fixed on the Kibana ISM repo and backported to all versions.
