### ISSUE TITLE
[Feature] Provide a built in index policy for ilm indexes.

### ISSUE THREAD

**Issue by rverma-jm** [opendistro-for-elasticsearch/index-management#225]
**Is your feature request related to a problem? Please describe.**
I can see opendistro creates indexes on a scheduled basis
1. .opendistro-alerting-alert-history-{{date}}
2. .opendistro-ism-managed-index-history-{{date}}

**Describe the solution you'd like**
A default Ilm policy which applies to these indexes to provide capability of rollover and delete

**Describe alternatives you've considered**
I think it's probably doable through manual configuration too, however I couldn't find any supportive docs.
For logging indexes I need to attach iam policy to fluentd pusher.

**Comment by dbbaughe** [comment]
Hi @rverma-jm,

I believe both ISM and Alerting in the latest master branches will automatically delete the history indices after a set period of time and they rollover without having to apply an ISM policy to them.

They are both defaulting to 30 days retention, but it is configurable.

e.g.

https://opendistro.github.io/for-elasticsearch-docs/docs/ism/settings/
opendistro.index_state_management.history.rollover_retention_period

Is there any specific reason you want ILM policies applied to them?
