### ISSUE TITLE
Add Open Distro Rollup Support

### ISSUE THREAD

**Issue by cashel1** [opendistro-for-elasticsearch/index-management#226]
Requesting rollup plugin in Open Distro that extends the capability currently offered by Elastic X-Pack Rollups.   Suggest the proposed approach utilize a Open Distro Job Scheduler extension as the mechanisim for defining, scheduling and exceuting rollup actions, and that Open Distro SQL be utilized (potential modification to this plugin required) to generate composite aggregations that would be necessary to generate usable rollups.  Request that the SQL aggregation query function support aggregations across one or more rollup indexes in addition to one or more search level indexes.

**Comment by dbbaughe** [comment]
Hi @cashel1,

We'll be writing an RFC in the coming weeks. If you have any additional requests/ideas please feel free to add them here and I'll try to incorporate them.

Thanks

**Comment by artemNN** [comment]
Rollup jobs really needed.

It would be very convenient if it were possible to collect metrics of derivatives. This is necessary for metrics, where each next value is the previous value + delta. Then, in these historical data, it will not be necessary to detail additional calculations.

**Comment by dbbaughe** [comment]
Hi @artemNN,

Could you go a bit more in depth around your use case/requirement? Any examples would be great so it can be considered in the initial design.

**Comment by jdratlif** [comment]
I am very interested in this plugin. In fact, we're trying to write a python script to do something like it now, but something built in to Open Distro would be much better than trying to maintain something out of tree.

We are using Elasticsearch to store network router and switch netflow data. There are hundreds of millions of records that get generated daily, but a lot of the granularity in the data is less useful over time, though we'd still like to keep some aggregate data for longer periods.

We would like to be able to specify a number of fields to keep (composite terms aggregation?) and some additional fields that have statistical data (count, sum, min, max, avg -- i.e. the stats aggregation). We want to be able to compact this data based on different time intervals. Right now, we're trying for hourly and daily aggregations, but more flexible time periods would be good.

It would also be extremely useful if we could run a search query that can search across both aggregate and non-aggregate data (at least for the rolled up fields).

Right now, our script is just running a composite aggregation with a stats sub-aggregate and storing the results into another index. We're aging out the aggregate indexes with ISM.

Thanks.

**Comment by neographikal** [comment]
I'm looking to ditch InfluxDB and switch to Elastic, this is what's needed when you have metrics data with high resolution. In my case it's energy data, for the day you might want data with a 1 minute resolution, but after a month or so hourly is enough. After a year daily would be enough.

To do this you would need to be able to do some calculations, calculating differences between counter values over time and only storing the difference as data.

**Comment by belkirdi** [comment]
Is this feature will be available in the next release ?

**Comment by dbbaughe** [comment]
Hi @belkirdi, this won't be available in the next ODFE release (1.10.1 I believe). It is currently in active development.
You can follow along here: https://github.com/opendistro-for-elasticsearch/index-management/tree/rollup-dev

**Comment by SKumarMN** [comment]
+1

**Comment by WassimDhib** [comment]
Hi

We are waiting for this plugin, it will be very useful for our use case.
We store access log and performance monitoring data. As the value of data decreases with age, we want to reduce the granularity of documents while leaving the possibility of making graphics to study historical trends.

here are some issues we encountered while attempting to do manual rollup:

-  search across both aggregate and non-aggregate data
-  search across aggregate data having different granularities (daily, hourly, weekly)
- weighting problem ( obviously `count of aggregated documents <> count of original documents`, but also `average of aggregated metric <> average of original metrics` if if the data is not uniformly distributed over time.
- numerical data behaves relatively well when aggregated, what about categorical data

**Comment by dbbaughe** [comment]
This has been released!

Please create new issues for any bug reports or feature/enhancement requests!
