### ISSUE TITLE
[BUG] Deleting all indices irrespective of the timestamp

### ISSUE THREAD

**Issue by naithagoni** [opendistro-for-elasticsearch/index-management#233]
**Describe the bug**
I have configured the policy to delete the old indices which are 2 days older but this configuration deleting even today's indexes.

**Here is my policy**
```
{
    "policy": {
        "policy_id": "delete_old_indices",
        "description": "A simple default policy that deletes old indicies.",
        "default_state": "open",
        "states": [
            {
                "name": "open",
                "actions": [
                    {
                        "open": {}
                    }
                ],
                "transitions": [
                    {
                        "state_name": "delete",
                        "conditions": {
                            "min_index_age": "2d"
                        }
                    }
                ]
            },
            {
                "name": "delete",
                "actions": [
                    {
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ]
    }
}
```

**Comment by dbbaughe** [comment]
Hi @naithagoni,

What version are you using? 

The logic simply looks at the creation date of the index in the metadata and uses that to check the index age which is the same logic used in rollover.

Does it always happen or just sometimes?

If you are on version 1.7.0+ then we [explicitly log](https://github.com/opendistro-for-elasticsearch/index-management/blob/master/src/main/kotlin/com/amazon/opendistroforelasticsearch/indexstatemanagement/step/transition/AttemptTransitionStep.kt#L102) what the conditions were that were evaluated as true which should help narrow it down.

**Comment by naithagoni** [comment]
Hi @dbbaughe 
Thanks for your comment. Yes, this is happening sometimes not always and I am using opendistro 1.7.0

**Comment by dbbaughe** [comment]
Hi @naithagoni,

Sorry for the late response. Are you able to check what the logs are saying? As noted above it should be logging
```kotlin
logger.info("$index transition conditions evaluated to true [indexCreationDate=$indexCreationDate," +
        " numDocs=$numDocs, indexSize=${indexSize?.bytes},stepStartTime=${stepStartTime.toEpochMilli()}]")
```

**Comment by dbbaughe** [comment]
If this is still an issue let us know and we can reopen; but there should be logs available in the latter versions that show what dates were used.
