### ISSUE TITLE
Index Management - Support Rollup

### ISSUE THREAD

**Issue by praveensameneni** [opendistro-for-elasticsearch/index-management#237]
The Rollup functionality summarizes old, high-granularity data into a reduced granularity format for long-term storage. By "rolling" the data up into a single summary document, historical data can be compressed greatly compared to the raw data and reduce costs.

**Comment by anirudha** [comment]
+1

**Comment by dbbaughe** [comment]
Closing in favor of https://github.com/opendistro-for-elasticsearch/index-management/issues/226
