### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Haneefh** [opendistro-for-elasticsearch/index-management#239]
When creating a policy the below error is thrown

Sorry, there was an error
no handler found for uri [/_opendistro/_ism/policies/hot?refresh=wait_for] and method [PUT]
<img width="817" alt="error-opendistro" src="https://user-images.githubusercontent.com/31154779/84756967-29ae1b80-afe1-11ea-82ea-6faf139bb24f.png">

**Comment by dbbaughe** [comment]
Hi @Haneefh,

Are you on AmazonES, ODFE, or self install? And which version?

**Comment by Haneefh** [comment]
Self install of ES version 7.7 and opendistro plugin version 1.8

**Comment by dbbaughe** [comment]
@Haneefh 

You have both the Kibana plugin and the Elasticsearch plugin installed right? From the pic it seems like you might of only installed the Kibana plugin.

Could you do GET _cat/plugins and post the response?

**Comment by dbbaughe** [comment]
Assuming that was the issue, if not feel free to reopen.
