### ISSUE TITLE
Index settings not respected on new index after rollover

### ISSUE THREAD

**Issue by Ricaz** [opendistro-for-elasticsearch/index-management#249]
Hi,

I discovered this because I'm only running 1 node, and want to keep health green by not having replicas (it goes yellow if the replica shard "fails").
I created an index with `"number_of_replicas": 0`, with a policy to rollover after 1h and delete after 2d:
```json
# PUT en-lille-test-000001
{
  "aliases": {
    "en-lille-test": {
      "is_write_index": true
    }
  },
  "settings": {
    "number_of_replicas": 0, 
    "index": {
      "opendistro": {
        "index_state_management": {
          "policy_id": "1hr-rollover",
          "rollover_alias": "en-lille-test"
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "timestamp": {
        "type": "date",
        "format": "epoch_second"
      }
    }
  }
}
```

And the policy:
```json
{
  "policy": {
    "policy_id": "1hr-rollover",
    "description": "Test policy, please delete me (yes really)",
    "last_updated_time": 1594283496710,
    "schema_version": 1,
    "error_notification": null,
    "default_state": "hot",
    "states": [
      {
        "name": "hot",
        "actions": [
          {
            "replica_count": {
              "number_of_replicas": 0
            }
          },
          {
            "rollover": {
              "min_index_age": "1h"
            }
          }
        ],
        "transitions": [
          {
            "state_name": "delete",
            "conditions": {
              "min_index_age": "2d"
            }
          }
        ]
      },
      {
        "name": "delete",
        "actions": [
          {
            "delete": {}
          }
        ],
        "transitions": []
      }
    ]
  }
}
```

After 1 hour, the index rolls over and the alias now points to `en-lille-test-000002`, but this new index was created with 1 replica, not 0.

**EDIT:**
I noticed mappings aren't transferred either. Here are the two indices (note the new one has default (?) values for mapping):
```json
{
  "en-lille-test-000001" : {
    "aliases" : {
      "en-lille-test" : {
        "is_write_index" : false
      }
    },
    "mappings" : {
      "properties" : {
        "message" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "timestamp" : {
          "type" : "date",
          "format" : "epoch_millis"
        }
      }
    },
    "settings" : {
      "index" : {
        "opendistro" : {
          "index_state_management" : {
            "policy_id" : "1hr-rollover",
            "rollover_alias" : "en-lille-test"
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "en-lille-test-000001",
        "creation_date" : "1594299951942",
        "number_of_replicas" : "0",
        "uuid" : "OTfGoG-xTQKHphIdV-Ps8g",
        "version" : {
          "created" : "7070099"
        }
      }
    }
  },
  "en-lille-test-000002" : {
    "aliases" : {
      "en-lille-test" : {
        "is_write_index" : true
      }
    },
    "mappings" : {
      "properties" : {
        "message" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "timestamp" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1594300852015",
        "number_of_shards" : "1",
        "number_of_replicas" : "0",
        "uuid" : "pqVha0SXTwqNMTmSXUPRxQ",
        "version" : {
          "created" : "7070099"
        },
        "provided_name" : "en-lille-test-000002"
      }
    }
  }
}
```
(`"number_of_replicas": 0` because I manually set it)
Note that `timestamp` turned back into a text field. 

Am I using it incorrectly? Are there any options to control the settings of the new index during rollover?

**Comment by Ricaz** [comment]
To add to this, I saw that only the original index shows up in the 'Managed Indices' table. Is this intentional? Wouldn't it actually be the new index that is considered managed?

**Comment by dbbaughe** [comment]
Hi @Ricaz,

Rollover does not roll over the index settings and mappings. It only deals with rolling over the alias by first creating a new index and then moving the alias over. If you'd like to have this new index consist of the same settings and mappings you should create a template that matches the index pattern. In the index template you can specify what settings and mappings any index that matches that pattern should adopt when being created. You can see some examples here:
https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/index-templates/

With that being said, since rollover does not roll your settings over it means that the policy_id in the index settings is also not moved over automatically. Similar to above, you just need to include the policy_id in your template so that all new indices created (in your case, en-lille-test-000002) will immediately apply that policy to the index.

**Comment by Ricaz** [comment]
Hi @dbbaughe, thanks for the quick reply.

I have clearly misunderstood the rollover functionality, but I don't recall making templates for all my indices in the original ES. Is the rollover process the same or am I mistaken?

**Comment by dbbaughe** [comment]
@Ricaz, it is the same rollover functionality. All ISM is doing is calling the rollover on your behalf when it evaluates to true.
Technically you can include mappings/settings directly in the rollover request as shown here: https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-rollover-index.html#rollover-index-settings-ex, but for ISM we preferred the usage of index templates.

**Comment by Ricaz** [comment]
I see, thanks! I would've probably gone for that if I knew it was possible, but I'll go with templates as that seems like the best practice.
