### ISSUE TITLE
Build in ttl for index rule 

### ISSUE THREAD

**Issue by mporracindie** [opendistro-for-elasticsearch/index-management#25]
As an enhancement i would like to ask for a build in ttl management tool for each index. 
The purpose of this would be to easily be able to set how mucho you would want to retain index data for each index.

**Comment by dbbaughe** [comment]
Hi @mporracindie,

This is possible with the index-management plugin we are currently developing. You will be able to specify how long an index should retain it's data by using the transitions and delete action. Feel free to follow along with the development in this repository.

**Comment by dbbaughe** [comment]
Closing this as ISM has been officially released in OD 1.3. You can use ISM state transitions + delete action to choose how long to keep the data in the index around for.
