### ISSUE TITLE
[BUG] Snapshot action not finishing

### ISSUE THREAD

**Issue by jgprogramming** [opendistro-for-elasticsearch/index-management#259]
Hey guys,

Since upgrading to version 1.9.0 we've noticed that out ILM pipelines are getting stuck in snapshot step. 

This is our pipeline definition
```
{
    "policy_id": "xxxxx.uat",
    "default_state": "Hot",
    "description": "Policy for application: xxxxx.uat",
    "states": [
        {
            "name": "Hot",
            "transitions": [
                {
                    "state_name": "Warm",
                    "conditions": {
                        "min_index_age": "5d"
                    }
                }
            ],
            "actions": [
                {
                    "rollover": {
                        "min_size": "40gb",
                        "min_index_age": "2d"
                    }
                }
            ]
        },
        {
            "name": "Warm",
            "transitions": [
                {
                    "state_name": "Delete",
                    "conditions": {
                        "min_index_age": "7d"
                    }
                }
            ],
            "actions": [
                {
                    "allocation": {
                        "require": {
                            "box_type": "warm"
                        },
                        "wait_for": false
                    }
                }
            ]
        },
        {
            "name": "Delete",
            "transitions": [],
            "actions": [
                {
                    "snapshot": {
                        "repository": "s3-repository",
                        "snapshot": "xxxxx.uat"
                    }
                },
                {
                    "delete": {}
                }
            ]
        }
    ]
}
```

Right now it looks like snapshots are created properly but ILM job is stuck in "Starting action snapshot and working on wait_for_snapshot".
```
{
  "xxxxx.uat-000049" : {
    "index.opendistro.index_state_management.policy_id" : "xxxxx.uat",
    "index" : "xxxxx.uat-000049",
    "index_uuid" : "4_Q4Uy7yTl-toBPohp-6aA",
    "policy_id" : "xxxxx.uat",
    "policy_seq_no" : 38378,
    "policy_primary_term" : 92,
    "rolled_over" : true,
    "state" : {
      "name" : "Delete",
      "start_time" : 1594714436556
    },
    "action" : {
      "name" : "snapshot",
      "start_time" : 1595583836562,
      "index" : 0,
      "failed" : false,
      "consumed_retries" : 0,
      "last_retry_time" : null,
      "action_properties" : {
        "snapshot_name" : "xxxxx.uat-2020.07.24-09:43:56.646"
      }
    },
    "retry_info" : {
      "failed" : false,
      "consumed_retries" : 0
    },
    "info" : {
      "message" : "Starting action snapshot and working on wait_for_snapshot"
    }
  }
}
```

And only logs we can see are related to IndexMetaDate not being able to update
![image](https://user-images.githubusercontent.com/20370084/88402203-14d85b00-cdcb-11ea-8155-ee0ae40cca08.png)

Is there a fix for this issue? Maybe we've missed something during update?

Regards

**Comment by dbbaughe** [comment]
Hey @jgprogramming,

Can you use the zip artifact from the latest commit to master which should still be the same ES version. Should be able to go to this link and use the artifact on top right.
https://github.com/opendistro-for-elasticsearch/index-management/runs/891807380

Issue was fixed here:
https://github.com/opendistro-for-elasticsearch/index-management/commit/41925f375cd02cfeb828815d148bf70f0a4f1b40#diff-3af37a8debc563e8f6ae63c3054e7d24R69

**Comment by jgprogramming** [comment]
Hey, thanks for response. Good to know that it's fixed already. Right now we're not able to upgrade since we're running custom version with allocate plugin but we'll schedule it for sure some time in the future.

**Comment by dbbaughe** [comment]
@jgprogramming 
One of the recent PRs I merged in actually unblocks the Allocation PR. It was blocked before because there was no way to write the multi-node integration tests and now we have a way to do it through gradle (and CI). Once I get the time I'll look into an integration test we can add to the PR, unless the original author wanted to take a stab at it.
