### ISSUE TITLE
Rollover with summarization/average/count using a specific fields

### ISSUE THREAD

**Issue by belkirdi** [opendistro-for-elasticsearch/index-management#296]
**Is your feature request related to a problem? Please describe.**
One of our concerns is we have an index with values in second interval. We want summarize/average the value to a minute/hour when the data is older than a specific date like (5days, 1 month, 1 year)

**Describe the solution you'd like**
We will like to have a policy that will allow us to do that

**Describe alternatives you've considered**
Use the job scheduler and create a service to handle the summarization of the values older than a specific date

**Additional context**
None

**Comment by dbbaughe** [comment]
Hi @belkirdi,

I will close this in favor of: https://github.com/opendistro-for-elasticsearch/index-management/issues/226

Just to note - we have started development on this. It will not be controlled by the same policy you use for ISM though, but it will be a separate job with it's own configuration along with an integration within ISM in the form of an action (so you have multiple ways to do a rollup).
