### ISSUE TITLE
List all policies via API

### ISSUE THREAD

**Issue by dmpe** [opendistro-for-elasticsearch/index-management#299]
**Is your feature request related to a problem? Please describe.**

Based on this https://opendistro.github.io/for-elasticsearch-docs/docs/ism/api/#get-policy, I would like to have a list API for listing all policies being present/stored in ELK.

Reason: `GET _opendistro/_ism/policies/policy_1` may be nice if you have strict rules about naming the policies, i.e. in that case you can simple enumerate them....but without some sort of regex. it would be hard to guess how to access **all** policies being active.

**Comment by dbbaughe** [comment]
Hi @dmpe,

We currently have an open issue tracking this here: https://github.com/opendistro-for-elasticsearch/index-management/issues/102
There is a workaround in the issue itself for now by just querying the index.
Will close this one in favor of that for now, thanks.
