### ISSUE TITLE
 Cann't register repository in S3

### ISSUE THREAD

**Issue by Andrew302** [opendistro-for-elasticsearch/index-management#3]
I need register my  bucket s3. Attached this code in devtools on kibana and shows this result.  Waht

![snap](https://user-images.githubusercontent.com/46787683/56118883-32353d00-5f6b-11e9-95b1-88f761a836cd.JPG)

**Comment by dbbaughe** [comment]
Hi @Andrew302,

If you never resolved the issue, you have incorrectly formatted JSON where the [x] is.

Drew
