### ISSUE TITLE
Allow Index management based on number of occurrence of rollover condition

### ISSUE THREAD

**Issue by mt1189** [opendistro-for-elasticsearch/index-management#300]
**Is your feature request related to a problem? Please describe.**
I am currently trying to figure out how to apply an ISM policy that will allow me to control indices based on size. There doesn't seem to be a function to allow for the deletion of indices once a size threshold is met, only by time. The data to be indexed varies wildly from hour to hour. One time chunk I'll have 1g then the next can have 20g. Since I only have limited storage, I can't go by index age.     

**Describe the solution you'd like**
 For example, I want to limit each index to 20gb and rollover to index *002 once the condition is met. I have a very stringent storage requirement so I can only devote 100gb to this index type. In theory, I want to delete the first Index once the number of rollovers reaches 6. This should always keep the maximum size to 100gb

**Describe alternatives you've considered**
I have considered letting rollover indices go indefinitely. I will have a script run in the background that will count the number of indices existing and delete the oldest if number of indices > 6. This should work but is not as clean and native as it should be.

**Additional context**
I know that time based management works for 99% of index considerations.  The cases to where you can only allocate a certain amount of storage for a given index is also needed for the last 1%.

**Comment by dbbaughe** [comment]
Hey @mt1189, I'm assuming this would resolve your use case if implemented?
https://github.com/opendistro-for-elasticsearch/index-management/issues/260

**Comment by mt1189** [comment]
Actually yes it would. I'm not sure why I didn't click that is was a duplicate of this when I was scanning the issues. Thanks for the link!
