### ISSUE TITLE
Add User object to Policy for future Security setup

### ISSUE THREAD

**Issue by bowenlan-amzn** [opendistro-for-elasticsearch/index-management#311]
add user object on policy model will help us filter who has the access to operate on the policy

policy would be read-only to everyone, but only user with certain roles can modify it.
so we will add filter logic in Index and Delete policy API

**Comment by dbbaughe** [comment]
User object has been added to managed index job when applying a policy to an index. Also stored in ISM template for index patterns auto creating jobs.
