### ISSUE TITLE
[BUG]  illegal_argument_exception when management policies are added to templates

### ISSUE THREAD

**Issue by sstephanou-bc** [opendistro-for-elasticsearch/index-management#356]
**Describe the bug**
When attaching index policies to the Wazuh templates `wazuh-monitoring-*` and `wazuh-alerts-4.x-*`, the indices created from those templates have the `illegal_argument_exception` error in multiple fields.

**Other plugins installed**
The plugins installed are the wazuh-manager v4.0.3-1, filebeat-oss v7.9.1, opendistroforelasticsearch-kibana v1.11.0, elasticsearch-oss v7.9.1, and opendistroforelasticsearch v1.11.0-1 which includes:
opendistro-anomaly-detection, opendistro-job-scheduler, opendistro-knn, opendistro_alerting, opendistro_index_management, opendistro_performance_analyzer, opendistro_security and opendistro_sql all v1.11.0 
as described in this [installation guide](https://documentation.wazuh.com/4.0/installation-guide/open-distro/all-in-one-deployment/all_in_one.html).

**To Reproduce**
1. Go to Index Management
2. Go to Index Policies
3. Click on Create policy
4. Create this simple policy with policy ID `simple_policy`:
```
{
    "policy": {
        "description": "A simple default policy.",
        "default_state": "hot",
        "states": [
            {
                "name": "hot",
                "actions": [
                    {
                        "rollover": {
                            "min_index_age": "7d"
                        }
                    }
                ],
                "transitions": [
                    {
                        "state_name": "warm"
                    }
                ]
            },
            {
                "name": "warm",
                "actions": [],
                "transitions": [
                    {
                        "state_name": "delete",
                        "conditions": {
                            "min_index_age": "90d"
                        }
                    }
                ]
            },
            {
                "name": "delete",
                "actions": [
                    {
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ]
    }
}
```
5. Go to Dev Tools
6. Attach the policy to the templates by executing the command
```
PUT _index_template/wazuh
{
  "index_patterns": ["wazuh-monitoring-*", "wazuh-alerts-4.x-*"],
  "template": {
    "settings": {      
      "opendistro.index_state_management.policy_id": "simple_policy"    
    }
  }
} 
```
7. The following day, e.g. `2020-12-11`, the indices `wazuh-monitoring-2020.12.11` and `wazuh-alerts-4.x-2020.12.11`, have the following error but in multiple fields, not just `status`:
```
Type    illegal_argument_exception
Reason  Text fields are not optimised for operations that require per-document field data like aggregations 
and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, 
set fielddata=true on [status] in order to load field data by uninverting the inverted index. Note that this 
can use significant memory.
```

**Expected behavior**
The expected behavior is to be able to attach policies to templates and indices be created from those templates without any errors. Ultimately, I would like to create a policy that deletes the indices after a certain amount of days.

**Desktop:**
 - OS: Linux
 - Browser: Chrome
 - Version: 87

**Additional Context:**
After examining the indices created, I believe the error is due to the following mapping:
```
            "mitre" : {
              "properties" : {
                "id" : {
                  "type" : "text",
                  "fields" : {
                    "keyword" : {
                      "type" : "keyword",
                      "ignore_above" : 256
                    }
                  }
                }
```
instead of the mapping 
```
            "mitre" : {
              "properties" : {
                "id" : {
                  "type" : "keyword"
                }
```
However, I am not 100% certain.

**Comment by dbbaughe** [comment]
@sstephanou-bc
A bit unclear if this is related to ISM? ISM wouldn't do anything to the index mappings.
Could you try removing the policy_id setting in the template and see if you still have the same issue or not?

**Comment by sstephanou-bc** [comment]
Hello @dbbaughe,
I started having this issue when I attached the policies to the templates so I thought this would be the problem. I removed the policy from the templates and will report back tomorrow if the problem persists.

**Comment by sstephanou-bc** [comment]
I removed the policy from the `wazuh-alerts-4.x-*` template and removed the `policy_id` setting from the `wazuh` template by executing the following command in Dev Tools:
```
PUT _index_template/wazuh
{
  "index_patterns": ["wazuh-monitoring-*"],
  "template": {
    "settings": {}
  }
}
```
The wazuh-alerts-4.x-2020-12-12 index is fine but the wazuh-monitoring-2020-12-12 has the  `illegal_argument_exception` issue. This means that the above command is causing the problem. Any clue as to why this is happening?

**Comment by sstephanou-bc** [comment]
I resolved the issue. I had to copy the whole template in the index template.
