### ISSUE TITLE
Support Elasticsearch 7.2

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/index-management#37]
To be done at the end of development/before initial release.

**Comment by lolcatlolcat** [comment]
ETA on when this plugin (and the corresponding kibana plugin) will be available for elastic 7.2.0?

**Comment by arnitolog** [comment]
also waiting for this plugin. Will it be released for ODFE 1.2?

**Comment by dbbaughe** [comment]
Hi @lolcatlolcat and @arnitolog,

The current master supports version 7.2 (or ODFE 1.2), but needs to be built by following the build instructions. We will have a release for 7.2 for this plugin on its own in the release tab in the future and are currently working on integrating this into the official ODFE distribution.

**Comment by dbbaughe** [comment]
1.2 releases are available on release tab. They will not be built into the ODFE 1.2 distribution, but you can add it as a custom plugin into that distribution. This is included in 1.3+ ODFE releases.
