### ISSUE TITLE
Specify index patterns for policies

### ISSUE THREAD

**Issue by wyllys66** [opendistro-for-elasticsearch/index-management#384]
It would be far more useful if policies could be applied to index patterns, so that as new ones are created (logstash, security logs, etc) on a daily basis the policies would automatically be applied.

Currently, it seems that we have to manually apply the policies to the indexes as they appear daily which is far from optimal.

**Comment by dbbaughe** [comment]
Hi @wyllys66,

You can currently use [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html) for this. This lets you specify an index pattern and the policy_id to be applied to them as they are created.

That being said, we are planning on removing support for the above and directly bake the template logic directly into the policies which @bowenlan-amzn is working on. Same behavior, just more control for ISM around security permissions.

**Comment by wyllys66** [comment]
Thanks for the update!

**Comment by wyllys66** [comment]
In case anyone is wondering (because it is not documented anywhere that I can find), here is an example of an index_template that applies a life cycle policy to any index matching the given pattern(s):

```
PUT _index_template/logstash_template
{
  "index_patterns": [
    "logstash-2021.*"
  ],
  "template": {
    "settings": {
      "index": {
        "opendistro": {
          "index_state_management": {
            "policy_id": "logstash_lifecycle"
          }
        }
      }
    }
  }
}
```
