### ISSUE TITLE
min_index_age question

### ISSUE THREAD

**Issue by tjbaker** [opendistro-for-elasticsearch/index-management#396]
From the docs:
`min_index_age - The minimum age of the index required to transition.`

Does this mean the minimum age of the index itself based on a creation timestamp, or does it mean the minimum age of the youngest document within the index?

For example, if I use monthly indexes like myindex-2021.01.01 being written to daily and use a 1m `min_index_age` transition, will the index transition to the next state on ~ Feb 1 because it has been 1m from index creation, or will it wait 1m from the last write to the index which would be `01/31 + 1m`?

The concern is that when using a 1m transition to delete non-critical indices that get daily writes, documents being written to the index will towards the end of the month will not live the full ~30 days.

Thanks in advance for the clarification.

**Comment by dbbaughe** [comment]
Hey @tjbaker, it is a creation date timestamp for the index when it is created. You can view it when doing `GET {index}/_search`.

Yes, if you had an index that represents a full months worth of data and it was set up to delete after 1M (1 month) then that data that came in at 1/31 would in fact be deleted shortly after. You could set the transition to be 2M so all data is there for _at least_ 1 month, although now you will of course have data from 1/1 exist for 2 months worth of time. Or you could split your indices into smaller daily indices to have that higher granularity.
