### ISSUE TITLE
Dashboard drilldown in OpenDistro

### ISSUE THREAD

**Issue by JujuElk** [opendistro-for-elasticsearch/index-management#403]
Hi, 

It would be awesome if we have drilldown feature in Open Distro. Make possible to navigate through dashboards by clicking on data from visualizations placed inside dashboards. It will allow users to have a better comprehension of their data, and make dashboard more user friendly. 

Thanks, 
Julien

**Comment by dbbaughe** [comment]
Hey @JujuElk, are you asking for a Kibana enhancement of Dashboards? I'm guessing this should be moved to generic community repo or Kibana repo.

What type of navigation are you referring to? i.e. let's say you do have a dashboard that shows your data and you click on it where do you want to be taken to? I think currently you can drill down by zooming in on charts and adding filters by clicking on certain visualizations.

**Comment by JujuElk** [comment]
Hi @dbbaughe, 

Yes I am asking for a Kibana enhancement of Dashboards. Ok to move it to Kibana repo. 

I mean the feature to easily open one dashboard from another dashboard by clicking on link that user set up in dashboard edition

**Comment by JujuElk** [comment]
Wrong place. Move it here : https://github.com/opendistro-for-elasticsearch/community/issues/248
