### ISSUE TITLE
Default action timeout documentation

### ISSUE THREAD

**Issue by jsirianni** [opendistro-for-elasticsearch/index-management#404]
**Is your feature request related to a problem? Please describe.**

No problem or bug. I would like to see documentation for default action timeouts. 

**Describe the solution you'd like**

I have segments failing to merge before timeout. I intend to set the timeout, but I am not sure what the default timeout is.

**Describe alternatives you've considered**

Searching the source code.

**Additional context**

I am using version 1.10.1

**Comment by dbbaughe** [comment]
Hey @jsirianni,

There is a default timeout of 12 hours in the wait for force_merge step.
https://github.com/opendistro-for-elasticsearch/index-management/blob/3968342341786c555458559d15c9ca6b4ce4d56c/src/main/kotlin/com/amazon/opendistroforelasticsearch/indexmanagement/indexstatemanagement/step/forcemerge/WaitForForceMergeStep.kt#L75-L76

@ashwinkumar12345, can we update docs with the default 12 hour timeout for force merge action?
