### ISSUE TITLE
[BUG] 1.12: Applying ISM policy triggers fault

### ISSUE THREAD

**Issue by ict-one-nl** [opendistro-for-elasticsearch/index-management#406]
**Describe the bug**
I created the following index policy:

```
{
    "policy": {
        "policy_id": "telegraf-delete-1d",
        "description": "A simple default policy that changes the replica count between hot and cold states.",
        "last_updated_time": 1613727775366,
        "schema_version": 1,
        "error_notification": null,
        "default_state": "hot",
        "states": [
            {
                "name": "hot",
                "actions": [
                    {
                        "replica_count": {
                            "number_of_replicas": 0
                        }
                    }
                ],
                "transitions": [
                    {
                        "state_name": "cold",
                        "conditions": {
                            "min_index_age": "1d"
                        }
                    }
                ]
            },
            {
                "name": "cold",
                "actions": [
                    {
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ]
    }
}
```

Applying this through the UI (Indices -> appy policy) gives the following logging:

`elasticsearch [2021-02-19T09:37:02,040][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job QAS1uBu2QyatrZYmZoRxeQ on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,040][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job 8GoUnKh-RQGhK60DZ6BtLg on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,040][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job pnYPr2wsRgGEMf5JuhKyFQ on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,041][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job _SaT4oQoTOqN3ej1cZjucA on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,073][INFO ][c.a.o.j.s.JobScheduler   ] [elasticsearch-1] Scheduling job id _SaT4oQoTOqN3ej1cZjucA for index .opendistro-ism-config .                                                                      ││ elasticsearch [2021-02-19T09:37:02,073][INFO ][c.a.o.j.s.JobScheduler   ] [elasticsearch-1] Scheduling job id UjbhLLgmRGOgmEUSZ1tBlA for index .opendistro-ism-config .                                                                      ││ elasticsearch [2021-02-19T09:37:02,074][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job yAoESYhxRFqPaOkOwvyO_A on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,075][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job UjbhLLgmRGOgmEUSZ1tBlA on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,075][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job q7VRNsH5SZWWPrVq_zaBgw on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,075][INFO ][c.a.o.j.s.JobScheduler   ] [elasticsearch-1] Scheduling job id 33naRUNfTTytWNLtx_Uhqw for index .opendistro-ism-config .                                                                      ││ elasticsearch [2021-02-19T09:37:02,075][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job 33naRUNfTTytWNLtx_Uhqw on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,075][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job 9R86WyXzTL2ufaeCFL9c1A on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,075][INFO ][c.a.o.j.s.JobScheduler   ] [elasticsearch-1] Scheduling job id 9R86WyXzTL2ufaeCFL9c1A for index .opendistro-ism-config .                                                                      ││ elasticsearch [2021-02-19T09:37:02,076][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job TrYQzM4wQrGM4gP9g475tg on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,076][INFO ][c.a.o.j.s.JobScheduler   ] [elasticsearch-1] Scheduling job id vJasNETOS-qlUqRWWUrOvQ for index .opendistro-ism-config .                                                                      ││ elasticsearch [2021-02-19T09:37:02,076][INFO ][c.a.o.j.s.JobScheduler   ] [elasticsearch-1] Scheduling job id TrYQzM4wQrGM4gP9g475tg for index .opendistro-ism-config .                                                                      ││ elasticsearch [2021-02-19T09:37:02,077][INFO ][c.a.o.j.s.JobScheduler   ] [elasticsearch-1] Scheduling job id OtAW9G-gRc2CQYXobKyJGQ for index .opendistro-ism-config .                                                                      ││ elasticsearch [2021-02-19T09:37:02,077][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job vJasNETOS-qlUqRWWUrOvQ on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,077][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job OtAW9G-gRc2CQYXobKyJGQ on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,077][INFO ][c.a.o.j.s.JobScheduler   ] [elasticsearch-1] Scheduling job id 3_qRy6SFS42bvUCHZmnEoQ for index .opendistro-ism-config .                                                                      ││ elasticsearch [2021-02-19T09:37:02,077][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job VR_qHwJ2QSC1hafleVx7Lg on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,077][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job 3_qRy6SFS42bvUCHZmnEoQ on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,078][INFO ][c.a.o.j.s.JobScheduler   ] [elasticsearch-1] Scheduling job id jCKXDEgLTCi_UlrrAgXJzw for index .opendistro-ism-config .                                                                      ││ elasticsearch [2021-02-19T09:37:02,078][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job jCKXDEgLTCi_UlrrAgXJzw on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,078][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job d1SP3DK0QpS9C5LzVe8sgw on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,078][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job vcBhO31NQlWBY1A-lrLr6w on index .opendistro-ism-config                                                                   ││ elasticsearch [2021-02-19T09:37:02,079][INFO ][c.a.o.j.s.JobSweeper     ] [elasticsearch-1] Indexing failed for job UsMWSsw4R5-p3QJ6nJuFDQ on index .opendistro-ism-config`

Job status is stuck on initializing:

![image](https://user-images.githubusercontent.com/2643715/108487916-10f8b280-72a0-11eb-97f0-b18738f29957.png)

**Other plugins installed**
Standaard 1.12 docker containers

**To Reproduce**

**Expected behavior**
Index policy is applied or a clear fault pops up with a job status failed in UI.

**Screenshots**

**Desktop (please complete the following information):**
Docker v1.12 containers running in kubernetes with a 3 node cluster

**Additional context**

**Comment by dbbaughe** [comment]
Hey @ict-one-nl,

Can you paste a copy of your index mappings for the `.opendistro-ism-config` index?

**Comment by ict-one-nl** [comment]
Made sure we are running 1.12.0:

![image](https://user-images.githubusercontent.com/2643715/108589614-71025e00-735f-11eb-9a5a-dbc440e342d9.png)

it seems I do not have the Index:

![image](https://user-images.githubusercontent.com/2643715/108590224-8fb62400-7362-11eb-8764-4b0a65fe82e1.png)

![image](https://user-images.githubusercontent.com/2643715/108590244-aa889880-7362-11eb-8464-cc5583be91f3.png)

It is a fresh cluster (new persistent volume claims) where the security tool has been run:

![image](https://user-images.githubusercontent.com/2643715/108590318-1d920f00-7363-11eb-9ca7-45434f21bd7a.png)

**Comment by ict-one-nl** [comment]
Okay, this is weird:

Index is there now:

![image](https://user-images.githubusercontent.com/2643715/108620204-d66f5100-742a-11eb-83ea-c3280521231a.png)

Applying the ILM policy with an template does work now.

**Comment by dbbaughe** [comment]
Hey @ict-one-nl,

Seems like things are working now.. a bit confused on steps here to replicate the issue though.
Is this something you are able to replicate yourself? My best guess before were your mappings were incorrect for the index perhaps from an index template with `index_patterns: [*]`, but if it's working now that doesn't seem to be the issue.

**Comment by ict-one-nl** [comment]
I will be building a new cluster (1.13.0) later this week, will try it again

**Comment by dbbaughe** [comment]
Any update on this @ict-one-nl ?

**Comment by ict-one-nl** [comment]
I've set up several new clusters with 1.13 and haven't seen it since. Maybe it has something to do with the upgrade. Will be on the lookout.

Sorry for the late reply, busy weeks.

**Comment by ict-one-nl** [comment]
Not relevant anymore
