### ISSUE TITLE
Download URL of index-management plugin in documentaion is throwing 403 error

### ISSUE THREAD

**Issue by Sreevani871** [opendistro-for-elasticsearch/index-management#415]
DOC: https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#index-state-management

Trying to download the index management  plugin for elasticsearch-v7.10.0 but the following URL is forbidden.
https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro-index-management-1.12.0.1.zip.
Is the URL forbidden is expected?

**Comment by dbbaughe** [comment]
Hi @Sreevani871,

The plugin name was changed in 1.13 I believe, so the old URLs use an underscore instead of hyphen for the zip.

https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-index-management/opendistro_index_management-1.12.0.1.zip

**Comment by stockholmux** [comment]
@aetter  Docs are correct but for those who are trying to get previous version artifacts might be lead down a rocky path. Something we should document?

**Comment by aetter** [comment]
Every time we change the naming scheme, we should make copies of all the old artifacts with the new scheme. It's a totally reasonable assumption that people should be able to change the version string to anything and have it work. Documenting that it used to be an underscore for certain artifacts prior to x.y.z isn't the solution.

**Comment by Sreevani871** [comment]
Thanks! @dbbaughe
