### ISSUE TITLE
Implement Snapshot action

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/index-management#45]

**Comment by dbbaughe** [comment]
Steps:
[AttemptSnapshotStep] -> Call the snapshot API
- Don't fail this step if the snapshot API fails because of in progress
[WaitForSnapshotStep] -> Wait for snapshot to complete

Settings:
https://github.com/opendistro-for-elasticsearch/index-management/blob/master/src/main/resources/mappings/opendistro-ism-config.json#L181

**Comment by dabr-grapeup** [comment]
@dbbaughe Hi, I'm working at the design of this feature and I have one doubt about steps, do we really need `WaitForSnapshotStep` as separate step instead of just option for `AttemptSnapshotStep`? As I see the Snapshot API supports `wait for completion` option, it would be much easier to implement this ways and it would be more natural in terms of Snapshot API.

**Comment by dbbaughe** [comment]
Hi @dabr-grapeup,

The `WaitFor..` steps generally mimic `wait_for_completion` (or something similar if it doesn't exist natively). The reason we don't actually `wait_for` inside the `Attempt..` steps is because we don't want to have a single execution of a job actively waiting an extended period of time (which could be hours for some users indices). If there is some intermittent network issue and connection drops or node crashes then it's harder to recover from that in a single step that does both things, whereas if we break up the execution from the waiting then it becomes a bit more reliable and easier to retry from.

**Comment by dabr-grapeup** [comment]
Hi @dbbaughe,
I've extended my changes in Snapshot implementation with WaitForSnapshotStep and created PR. However I'm having problems with building it on your CI server as well as reproducing the problem on any local machine I have as I'm able to run all tests and build artifact without any problems.
After running command to reproduce:
`./gradlew ':integTestRunner' --tests "com.amazon.opendistroforelasticsearch.indexstatemanagement.action.SnapshotActionIT.test basic" -Dtests.seed=5F6526A5066301FB -Dtests.security.manager=false -Dtests.locale=ms-BN -Dtests.timezone=America/Mexico_City -Dcompiler.java=12 -Druntime.java=12`
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/dabr/workspace/adidas/index-management/build.gradle' line: 45

* What went wrong:
A problem occurred evaluating root project 'opendistro-for-elasticsearch-index-management'.
> Failed to apply plugin [id 'elasticsearch.esplugin']
   > A problem occurred starting process 'command '/bin/jrunscript''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'opendistro-for-elasticsearch-index-management'.
> Must specify license and notice file for project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```
Any ideas how to fix it?

**Comment by dbbaughe** [comment]
Hi @dabr-grapeup,

I checked out your PR ontop of master branch and I get the same errors as in the CI.
It looks like you might be testing it against an earlier version locally? Could you try updating your branch to the latest and try again.

Thanks,
Drew

**Comment by dabr-grapeup** [comment]
You're right, rebased onto master and have the same issue. It's fixed now and ready for review. :)

**Comment by dbbaughe** [comment]
This has been merged:
https://github.com/opendistro-for-elasticsearch/index-management/pull/135
