### ISSUE TITLE
[BUG] Trying to add setting ‘opendistro.index_state_management.rollover_alias’ throws an error

### ISSUE THREAD

**Issue by hatedabamboo** [opendistro-for-elasticsearch/index-management#459]
I am trying to set up rollover action for a policy, but when creating rollover alias for index, kibana throws an error:

> [illegal_argument_exception] Invalid field: [settings] found in ISMTemplate.

Removing this setting concludes creation of a policy, however rollup jobs fail because of absence of rollover alias.
Here how looks this part of policy template:
```        "ism_template": {
            "index_patterns": [
                "logstash-*"
            ],
            "priority": 100,
            "settings": {
                "opendistro.index_state_management.rollover_alias": "logs"
            },
            "last_updated_time": 1628182003809
        }
```
I am using opendistroforelasticsearch-kibana 1.13.2.

**Comment by dbbaughe** [comment]
Settings aren't supported in the ism_template in the policy.
You have to move that part (rollover_alias) into an index template
https://opendistro.github.io/for-elasticsearch-docs/docs/elasticsearch/index-templates/
