### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by gittygoo** [opendistro-for-elasticsearch/index-management#95]
Just came across this and wanted to try it out, there is nearly no documentation for it which makes it quite hard to even evaluate.

Would be nice to have some more documentation with examples for the newcomers like me :)

As an example i was able to set it up eventually, but now stuck on "Still initializing, please wait a moment" for quite a few minutes (on an index with only 112 documents). I have no idea WHAT it is initializing :)

**Comment by dbbaughe** [comment]
Hi @gittygoo,

We are preparing documentation for this plugin :).
I'll comment/close this once it has been published!

Drew

**Comment by gittygoo** [comment]
Thanks @dbbaughe is this still in development or is version V1.1.0.0 suppposedly working? 

I am doing the following:

1. creating a default policy (with whatever is there as default and naming it "default")
2. Clicking on an indice and adding the "default" policy to it and a rollover alias "rolloveralias"
3. Going to managed indices they either get stuck on "Initializing" or "Attempting to rollover"

My indexes are small since this is just a test cluster

**Comment by dbbaughe** [comment]
Hi @gittygoo,

We are done in terms of development for the initial release and are doing a round of bug testing at this point. I looked into your issue and it does look like it was a bug on the Kibana plugin side with the rollover_alias not being set. You should be able to use the native elasticsearch API to add the setting `"opendistro.index_state_management.rollover_alias": "your_rollover_alias",` manually to the index in the mean time to proceed with testing. Thanks for the help! We will release updated versions with bug fixes.

**Comment by sathomps** [comment]
Do you have a cURL example for creating a simple policy and associating it to a index template?

**Comment by dbbaughe** [comment]
Hi @sathomps,

Here's a quick example:

```
// creates a policy w/ policy_id ingest_policy
curl -X PUT localhost:9200/_opendistro/_ism/policies/ingest_policy -H 'Content-Type: application/json' -d '{"policy":{"description":"ingesting logs","schema_version":1,"default_state":"ingest","states":[{"name":"ingest","actions":[{"rollover":{"min_doc_count":"5"}}],"transitions":[{"state_name":"search"}]},{"name":"search","actions":[],"transitions":[{"state_name":"delete","conditions":{"min_index_age":"5m"}}]},{"name":"delete","actions":[{"delete":{}}],"transitions":[]}]}}'

// Creates this policy
{
  "policy": {
    "description": "ingesting logs",
    "schema_version": 1,
    "default_state": "ingest",
    "states": [
      {
        "name": "ingest",
        "actions": [
          {
            "rollover": {
              "min_doc_count": "5"
            }
          }
        ],
        "transitions": [
          {
            "state_name": "search"
          }
        ]
      },
      {
        "name": "search",
        "actions": [],
        "transitions": [
          {
            "state_name": "delete",
            "conditions": {
              "min_index_age": "5m"
            }
          }
        ]
      },
      {
        "name": "delete",
        "actions": [
          {
            "delete": {}
          }
        ],
        "transitions": []
      }
    ]
  }
}
```

```
// Creates an index called "some_index" that has the "policy_id" setting set to the policy_id from above
curl -X PUT localhost:9200/some_index -H 'Content-Type: application/json' -d '{ "settings": { "opendistro.index_state_management.policy_id": "ingest_policy", "number_of_shards": 1, "number_of_replicas": 0 } }'
```

As for using index templates, feel free to just follow the ES documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/current//indices-templates.html

The only thing you would need to add is the `"opendistro.index_state_management.policy_id"` in the settings along w/ the policy_id representing which policy you want those indices to adopt when they are created.

And as an update for others, we are still working on our documentation, sorry for the delay!

**Comment by sathomps** [comment]
Thanks - that's what I was looking for, the policy endpoint and opendistro props.

**Comment by dbbaughe** [comment]
Yes @sathomps, this has not been integrated into any of the Open Distro distributions yet. 
It is ready to be consumed as an individual plugin though, which means as long as you can install any custom plugins you should be able to install this one too.

**Comment by dbbaughe** [comment]
Closing this as there are official docs available here:
https://opendistro.github.io/for-elasticsearch-docs/docs/ism/

**Comment by ericson-cepeda** [comment]
> Hi @gittygoo,
> 
> We are done in terms of development for the initial release and are doing a round of bug testing at this point. I looked into your issue and it does look like it was a bug on the Kibana plugin side with the rollover_alias not being set. You should be able to use the `Add rollover alias` UI modal on the `Managed indices` page or the native elasticsearch API to add the setting `"opendistro.index_state_management.rollover_alias": "your_rollover_alias"` manually to the index in the mean time to proceed with testing. Thanks for the help! We will release updated versions with bug fixes.

Does is it mean that despite adding `"opendistro.index_state_management.policy_id"` in an index template, `"opendistro.index_state_management.rollover_alias": "your_rollover_alias"` won't be managed automatically once a rollover transition is applied? 

For instance, having a template index pattern `msp-*` (where * is a number) impedes having a rollover alias msp-*-alias for each values that `*` can take applied automatically. Correct?

**Comment by dbbaughe** [comment]
Hey @ericson-cepeda,

Sorry, didn't full understand this part of the question:
> For instance, having a template index pattern msp-* (where * is a number) impedes having a rollover alias msp-*-alias for each value that * can take applied automatically. Correct?

**Comment by ftorto** [comment]
Hi @dbbaughe, I have same question as @ericson-cepeda so I'll try to rephrase. Since our template is instantiated across several set of indices (each having a independent lifecycle), we could not figure how to setup a correct rollover alias in it.

With an example (I don't what MSP exactly means but it doesn't matter for this example):
* Create a `template_MSP`
* to manage MSP customers, we create 1 index per customer following the template. Each customer index has its own lifecycle
  * `MSP_customerA-00001` has the rollover alias set to `MSP_customerA`
  * `MSP_customerB-00001` has the rollover alias set to `MSP_customerB`
* When  `MSP_customerA-00001` rolls over to  `MSP_customerA-00001`, we could rely on the ISM mecanism to automatically fill the `MSP_customerA-00002` "rollover index" setting with the one already present in `MSP_customerA-00001`. So applying `MSP_customerA` rollover alias to 2nd index

Since `MSP_customerB` has a different lifecycle from `MSP_cutomerA`, we can't write the rollover alias directly in the shared template

**Comment by jackmead515** [comment]
Is this continued anywhere else? Still couldn't figure this out. I tried creating a template with an alias, without an alias, with the opendistro settings, without, creating an index without template, with template, with alias, without alias, still nothing. Fundamentally broken on my end. AWS ES Service 7.4.

**Comment by amirtal-cp** [comment]
this is still unanswered in the official docs.
i.e. is there any way to have a dynamic value for: 'index.opendistro.index_state_management.rollover_alias' 
when using daily indices, this means we need a new template for each day.

**Comment by seb-koch** [comment]
I got exactly the same issue. My indices are created daily by fluentd and the elasticsearch output plugin. So i got indices like fluentd-20201117, fluentd-20201116, fluentd-202011...

Is there any way to do the rollover automatically or to set the required alias through the index template that is applied?

**Comment by jeyaramji** [comment]
@seb-koch,@amirtal-cp , 
In to same situation(fluentd + ES). If you have managed to make it working( rollover automatically), can you please let us know?

**Comment by amirtal-cp** [comment]
please note this configuration is working for `image: quay.io/fluentd_elasticsearch/fluentd:v2.8.0`
```
            gem install fluent-plugin-aws-elasticsearch-service -v 2.4.0 &&
            gem install fluent-plugin-rewrite-tag-filter -v 2.3.0 &&
            gem install fluent-plugin-elasticsearch -v 4.0.9 &&
            /run.sh
```
(we did have issues when migrating this to later version)

fluentd output.conf:
```
      logstash_format true
      logstash_prefix kubernetes-${tag[0]}

      # Rollover index config
      index_name    kubernetes
      rollover_index    true
      application_name    ${tag[0]}
      index_date_pattern    "now/d{yyyy.MM.dd}"
      deflector_alias    kubernetes-${tag[0]}-%Y.%m.%d

      # Index template
      template_name      kubernetes-${tag[0]}-%Y.%m.%d
      template_file      /etc/fluent/config.d/es_index_template-1_month_retention_with_rollover.json
      customize_template <<NAMESPACE>>:${tag[0]},<<YYYYMMDD>>:%Y.%m.%d
      template_overwrite true

      <buffer tag,time>
      ...buffer settings...
      </buffer>
```

es_index_template-1_month_retention_with_rollover.json:
```
{
  "order" : 20,
  "index_patterns" : ["kubernetes-<<NAMESPACE>>-<<YYYYMMDD>>-*"],
  "settings" : {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "opendistro.index_state_management.policy_id": "1_month_retention_with_rollover",
    "opendistro.index_state_management.rollover_alias": "kubernetes-<<NAMESPACE>>-<<YYYYMMDD>>"
  }
}
```

* policy 'policy_id' should be created manually.
* buffer by 'tag' and 'time' is required to allow for substitution of '%Y.%m.%d'
* ${tag[0]} contains kubernetes namespace:
```
    <match kubernetes.**>
      @id rewrite_namespace
      @type rewrite_tag_filter
      @log_level debug
        <rule>
          key $['kubernetes']['namespace_name']
          pattern ^(.+)$
          tag $1.${tag}
        </rule>
    </match>
```

**Comment by jeyaramji** [comment]
@amirtal-cp , Thank you so much. Let me give it a try.

**Comment by JohnMops** [comment]
@amirtal-cp You saved us 55 years of troubleshooting ,thank you !
